### ISSUE TITLE
Create a Navbar

### ISSUE THREAD

**Issue by PriyanshuRj** [devtayade/Product-Designer-Portfolio-#23]
A navbar is an important aspect of design this site is currently lacking a navbar. Please allow me to add a navbar to the site.

**Comment by devtayade** [comment]
go ahead

**Comment by devtayade** [comment]
@PriyanshuRj any update ?

**Comment by PriyanshuRj** [comment]
Working on it.

**Comment by PriyanshuRj** [comment]
#28 Please review this PR
